---
- hosts: webservers

  tasks:
    - name: install tomcat
      ansible.builtin.yum:
        name:
          - tomcat
          - tomcat-webapps
          - tomcat-admin-webapps
          - tomcat-docs-webapp
        state: installed

    - name: start and enabled service
      ansible.builtin.service:
        name: tomcat
        state: started
        enabled: true

...
