---
- name: install apache
  ansible.builtin.yum:
    name: httpd
    state: installed

- name: start and enabled service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: copy file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/www/html/
  loop:
      - index.html
      - alpha.html
      - beta.html
      - gama.html
- name: reconfigure port number
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart httpd

...
